name: SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests, generate coverage and report files
        run: go test ./... -coverpkg=./... -coverprofile=coverage.out --json > test-report.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          args: "--timeout 5m --output.checkstyle.path golangci-lint-report.xml"

      - name: Analyze project and upload coverage
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
